import { IProduct } from 'src/app/product/product.model';

export const products: IProduct[] = [
  {
    id: 1,
    src: 'https://shopivate.pk/wp-content/uploads/2023/08/1000236536.jpg',
    name: 'Head Phone',
    price: 35,
    category: 'Electronics',
    description: 'best headphone with ultra battery duration',
  },
  {
    id: 2,
    src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr7Hub0YN94UCKfl9iAB49vaRO0ieA-Cjx0KxLKVtjZnMqk51a2I4618Tnr-KnzbGJ00s&usqp=CAU',
    name: 'Keyboard',
    price: 45,
    category: 'Electronics',
    description: 'best Keyboard with ultra battery duration',
  },
  {
    id: 3,
    src: 'https://images.priceoye.pk/yolo-pulse-bluetooth-speaker-pakistan-priceoye-bh4h7.jpg',
    name: 'Bluetooth Speaker',
    price: 15,
    category: 'Electronics',
    description: 'best Speaker with ultra battery duration',
  },
  {
    id: 4,
    src: 'https://www.popsci.com/uploads/2021/03/24/Backlit_Compueter_Laptop.jpg?auto=webp',
    name: 'Led Tv',
    price: 25,
    category: 'Electronics',
    description: 'best Led Tv with ultra battery duration',
  },
  {
    id: 5,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 6,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 7,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },

  {
    id: 8,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 9,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 10,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 11,
    src: 'https://hips.hearstapps.com/hmg-prod/images/index-online-64da7782717b2.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*',
    name: 'Summer Wear',
    price: 55,
    category: 'Clothing',
    description: 'best men summer wear',
  },
  {
    id: 12,
    src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5f2VGE3tXT1-LuhpTh8JJVg6I3Igx0eTe1A6OTyrNPogFz2DOKmyHzBR-gPK_e8Uqoxg&usqp=CAU',
    name: 'Sweater',
    price: 45,
    category: 'Clothing',
    description: 'best winter sweater',
  },
  {
    id: 13,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 14,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 15,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 16,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 17,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 18,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 19,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },

  {
    id: 20,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 21,
    src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyyorrFcmEZUsGZ9LgzesSFCx-cQid1r90Ew&usqp=CAU',
    name: 'Bedminton',
    price: 30,
    category: 'Sport',
    description: 'best bedminton with long use duration',
  },
  {
    id: 22,
    src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsci_wzbKJi3r4B2KNLn1UMUkbxmmUdhADSw&usqp=CAU',
    name: 'Basketball',
    price: 30,
    category: 'Sport',
    description: 'best basketball with long use duration',
  },
  {
    id: 23,
    src: 'https://play-lh.googleusercontent.com/sGLRNk9RIEPSsh8I8ZGiWnNYXcDTYkT7vPbfbn-7F-iXUWj9Q01Eh8SZfp014h22aA',
    name: 'Women Accessories',
    price: 30,
    category: 'Accessories',
    description: 'best women Acccessories with long use duration',
  },
  {
    id: 24,
    src: 'https://i.ebayimg.com/images/g/bRkAAOSwpaVkazHt/s-l400.jpg',
    name: 'Glasses',
    price: 30,
    category: 'Accessories',
    description: 'best women Acccessories with long use duration',
  },
  {
    id: 25,
    src: 'https://furniturehub.pk/wp-content/uploads/2021/04/1750-TRIANGLE-DINING-TABLE.jpg',
    name: 'Dining Table',
    price: 30,
    category: 'Furniture',
    description: 'best state of the art Dining Table.',
  },
  {
    id: 26,
    src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLxRNNivBW5z_ksnpUpYR2aSgtViFUBjpN9w&usqp=CAU',
    name: 'Bed Set',
    price: 30,
    category: 'Furniture',
    description: 'best state of the art Bed Set.',
  },
];
